### PR TITLE
Feature/api validation

### PR DESCRIPTION
**Pull request by anishmu20**
This pull request adds API validation for the Book, Borrowing, and Member modules. I have validated all the API endpoints that accept data related to these modules and have also handled the exceptions associated with these actions. This ensures that the API endpoints return appropriate responses for valid and invalid data, improving the robustness and reliability of the API.
i have tested api using the postmen .  

issues #81 

validation-1

exception handle
)
InvalidResponse

### CODE REVIEW

**Comment by Guhapriya01** [comment]
Hi @anishmu20,

Great job on the validations! Could you please add similar validations to `UpdatePasswordDto` as well? Thanks!

**Comment by anishmu20** [comment]
hii  @Guhapriya01  

The changes have been implemented as advised. Validation has been applied only to the newPassword field in the UpdatePasswordDto, ensuring it meets specified security requirements. The currentPassword field remains unvalidated in this DTO, as it is assumed to have already been validated and securely stored in the database.
updatePasswordDTo
)

**Comment by Guhapriya01** [comment]
Hi @anishmu20,

I reviewed your work, and thanks for making those changes!

Just make these 2 changes:

1. Add `@NotBlank` to the ISBN field in the Book DTO, as it's throwing an error when not passed.
2. Remove `@NotBlank` from the role field in the Members DTO, as it's not required.

Once these changes are made, we can proceed with the merge!

Thanks!

**Comment by anishmu20** [comment]
changes done !!

**Review by Guhapriya01 — APPROVED** [review]

**Comment by Guhapriya01** [comment]
Hi @anishmu20,

Thank you for your thorough work on adding validations across all the key DTOs. The comprehensive validation will greatly enhance data integrity across the API.

**Level Update:** Although initially marked as Level 2, this contribution has been recognized as **Level 3** due to the extensive impact and effort involved in implementing validations across multiple DTOs.

Looking forward to more collaborations. Thanks again for your contribution! 😊

**Pull request merged**
