### PR TITLE
Added backend functionalities for newsletter signup.

### PR DESCRIPTION
**Pull request by shreya5653**
#73 

NewsletterSubscriber Entity:
Implemented the entity to represent subscribers in the database.

NewsletterService:
Created the service layer to handle business logic for email subscriptions.
Added email validation logic to ensure correct email formats.

NewsletterController:
Developed the controller to manage incoming subscription requests.
Integrated error handling to return appropriate messages for invalid email inputs.

NewsletterRepository:
Added the repository to manage database operations related to email subscriptions.
Error Handling Improvements:

Enhanced error responses for invalid email formats to improve user experience.

Testing and Validation:
Tested all API endpoints thoroughly using Postman.
Verified that the signup flow works correctly from end to end.
Ensured the confirmation message is displayed upon successful subscription.

### CODE REVIEW

**Comment by Guhapriya01** [comment]
@shreya5653, great job on the newsletter functionality! Just a small suggestion: the email validation in the controller seems redundant as it's already handled in the service. It might be better to remove it from the controller for cleaner code.

**Comment by Guhapriya01** [comment]
Also, I think it would be great to add an unsubscribe feature. We could create a new endpoint in the `NewsletterController` for unsubscribing, along with the necessary logic in the `NewsletterService`. This would give users the option to easily manage their subscriptions. Let me know what you think!

**Comment by shreya5653** [comment]
@Guhapriya01

Thank you so much for the feedback! I’ll go ahead and remove the redundant email validation code from the controller to keep it clean and focused.

I also love the idea of having an unsubscribe endpoint! Instead of a button on the webpage, I plan to include an unsubscribe link in the emails we send. Each email will contain a unique token-based link, which will allow users to unsubscribe seamlessly with a single click. However, I haven’t worked on this kind of feature before, so it might be a bit complex, and I’ll need to learn more to implement it effectively.

Could you let me know which approach works for you or if you have any further suggestions? I’d be happy to discuss any other ideas you have to enhance this feature!"

**Comment by Guhapriya01** [comment]
@shreya5653, that sounds like a great approach! Including an unsubscribe link in the emails is definitely a good idea. Feel free to take your time to explore how to implement it.

If you need any help, we can discuss possible solutions together.

**Comment by shreya5653** [comment]
@Guhapriya01, I’ve implemented the unsubscribe functionality for the newsletter and tested it using Postman. The unsubscribe link will be included in the emails sent to subscribers, and I aimed to keep the code as non-redundant as possible. If you're interested, I’d love to take on the next feature regarding the actual sending of emails by creating a new issue. Let me know!

**Review by Guhapriya01 — APPROVED** [review]

**Comment by shreya5653** [comment]
> Hey @shreya5653 ! I reviewed your PR, and it looks great! I've merged it. Thanks for keeping the code clean and well-commented. Feel free to go ahead and create the new issue for the email sending feature.
> 
> Looking forward to seeing your next contribution! 😊

@Guhapriya01 Thank you so much! 😊

**Pull request merged**
