### PR TITLE
Fixed #49: Added GitHub Workflow for Automatic Greetings

### LINKED ISSUE #49: [FEATURE] Automated Greeting Workflow
### Is this feature already requested?

- [X] I have checked "open" and "closed" issues, and this is not a duplicate.

### Feature Description

I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

Hey @ajaynegi45 please assign me this task

### Would you like to work on this feature?

Yes

### PR DESCRIPTION
**Pull request by samyak-aditya**
Fixed #49

**Description:**
This pull request introduces a new GitHub Action workflow named "Greetings." The workflow automatically greets users who open new issues or pull requests in this repository.

**Key Features:**
- When a new issue or pull request is created, a comment will be automatically added, greeting the user with the following message:
  > "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

### CODE REVIEW

**Review by ajaynegi45 — APPROVED** [review]
Hi @samyak-aditya,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I'm pleased to inform you that I have merged your pull request. Your changes looks fantastic, and it aligns perfectly with the project's design and usability goals. Great job!

If you have any more contributions or if there's anything else you'd like to work on in the future, please don't hesitate to let us know. Your efforts are valuable to the project's success.

Once again, thank you for your contribution! ❤️

**Comment by samyak-aditya** [comment]
Hi @ajaynegi45 ,

Thank you for the kind words and for merging my pull request! I’m glad to hear that my contributions align with the project's goals.

I’ll definitely look into additional GitHub workflows and potential bots that can enhance our contributor experience. I’ll keep you updated if I find anything that could be beneficial.

I appreciate the opportunity to contribute to this project and look forward to collaborating more in the future. If there are any specific areas you’d like me to focus on next, please let me know!

Thanks again for your support! ❤️

Best,  
Samyak

**Comment by ajaynegi45** [comment]
> Hi @ajaynegi45 ,
> 
> Thank you for the kind words and for merging my pull request! I’m glad to hear that my contributions align with the project's goals.
> 
> I’ll definitely look into additional GitHub workflows and potential bots that can enhance our contributor experience. I’ll keep you updated if I find anything that could be beneficial.
> 
> I appreciate the opportunity to contribute to this project and look forward to collaborating more in the future. If there are any specific areas you’d like me to focus on next, please let me know!
> 
> Thanks again for your support! ❤️
> 
> Best, Samyak

Hi @Samyak,

Thanks again for your awesome contributions! Since you're great with GitHub Actions, I’d suggest checking out some of my other projects here: https://bento.me/codiescoder. You can implement similar workflows across them. I’ve got a variety of exciting projects where streamlined workflows could really make a difference.

It would be great if you could focus on adding more workflows that simplify the contribution and code review process. For instance, when someone creates an issue or feature request, we could include this message in the greeting:

_"👋 Hey @${{ github.actor }}! Thank you for raising an issue. Your input helps us improve, and we appreciate your effort! 🚀
Our team will review it shortly, so stay tuned for updates._
_In the meantime, please take a moment to read the README.md to understand our project's mission and goals. Also, make sure to review the CONTRIBUTING.md to familiarize yourself with our contribution guidelines, especially if you're new to the project. This will help make the process smoother for everyone! 😊"_

Feel free to tweak it as needed!

Looking forward to collaborating more!

**Comment by samyak-aditya** [comment]
Hi @ajaynegi45 

Thank you for the encouragement and for sharing the link to projects! I’ve gone through some resources and I’m excited to implement the greeting update you suggested.

I’ll create a new issue to outline the changes I plan to make, including the message you suggested. This will help keep everything organized and allow us to track the implementation process.

Looking forward to enhancing the workflows further!

**Comment by samyak-aditya** [comment]
Hi @ajaynegi45 ,

I hope you're doing well! I wanted to check in to see if you need any kind of auto-labeler for new issues or pull requests created in your repository. Implementing an auto-labeler can help streamline the management of contributions and make it easier to categorize them.

Let me know your thoughts!

**Comment by samyak-aditya** [comment]
Hey @ajaynegi45 Please add labels "gssoc-ext" and "level2" so that my contribution gets counted 
it is not been counted till now because or the missing labels

**Pull request merged**
