### PR TITLE
Implemented Search Book Functionality

### PR DESCRIPTION
**Pull request by rishabhrawat05**
Hey! @Guhapriya01 
The Search Functionality has been implemented. Please review the code for further improvement and correctness
Here are some screenshots
{FCB6E6CD-66D1-4617-A0BD-A888176980E0}
{65E283C5-B4AA-4402-A303-909B59B685F7}
{A5241838-36B7-4658-855B-61DC400D2FF4}

### CODE REVIEW

**Comment by Guhapriya01** [comment]
@rishabhrawat05, Great job on the search functionality! Could you add a null or empty check for the `keyword` parameter in the `searchBook` method within the `BookService` class? This will help prevent unnecessary db queries when `keyword` is missing. Other than this, everything looks good.

Thanks for your effort on this!

**Comment by rishabhrawat05** [comment]
Hey! @Guhapriya01 
I have updated the search function to handle null checks for keyword. Please kindly review the changes
Here are some screenshots of updated improvements
image
image
image

**Review by Guhapriya01 — APPROVED** [review]

**Comment by Guhapriya01** [comment]
Hey @rishabhrawat05,

Thank you for updating the search function with null checks for the keyword! I reviewed the code, and everything looks perfect, so I’ve gone ahead and merged it.

Thanks again for your contribution! 😊

**Comment by rishabhrawat05** [comment]
> Hey @rishabhrawat05,
> 
> Thank you for updating the search function with null checks for the keyword! I reviewed the code, and everything looks perfect, so I’ve gone ahead and merged it.
> 
> Thanks again for your contribution! 😊

😊 Thank you @Guhapriya01. And just one suggestion as this search API is authenticated for users If you want users to search without login, you can go to the security config file and add this API and mark it permit for all.

**Comment by Guhapriya01** [comment]
> 😊 Thank you @Guhapriya01. And just one suggestion as this search API is authenticated for users If you want users to search without login, you can go to the security config file and add this API and mark it permit for all.

Thanks for the suggestion, @rishabhrawat05! 😊 That’s a great point. I’ll make the necessary changes in the security config to allow unauthenticated users to access the search API.

**Pull request merged**
