### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by neeru24**
I have added metrices table in the readme.

**Benefits:**

- Improves the overall presentation of the README.
- Encourages contributions by showcasing community involvement.

Kindly assign me this issue and merge it @ajaynegi45 

Thank you!!

image

### CODE REVIEW

**Comment by neeru24** [comment]
> I have added metrices table in the readme.
> 
> **Benefits:**
> 
> - Improves the overall presentation of the README.
> - Encourages contributions by showcasing community involvement.
> 
> Kindly assign me this issue and merge it @ajaynegi45 
> 
> Thank you!!
> 
> image
> 
@ajaynegi45 check it please

**Review by Devamani11D — CHANGES_REQUESTED** [review]
Hello @neeru24 !!
Your idea to showcase metrics is good and it looks very nice in the readme.
But Please consider placing that metrics table somewhere below contributors list i.e above the graph showing star history of Repo. And please consider keeping green color for Closed PR's number display.
Thank you 😄

**Comment by neeru24** [comment]
> Hello @neeru24 !!
> Your idea to showcase metrics is good and it looks very nice in the readme.
> But Please consider placing that metrics table somewhere below contributors list i.e above the graph showing star history of Repo. And please consider keeping green color for Closed PR's number display.
> Thank you 😄 

Sure, I'll do the changes soon and submit a PR

**Comment by neeru24** [comment]
> > Hello @neeru24 !!
> > Your idea to showcase metrics is good and it looks very nice in the readme.
> > But Please consider placing that metrics table somewhere below contributors list i.e above the graph showing star history of Repo. And please consider keeping green color for Closed PR's number display.
> > Thank you 😄
> 
> Sure, I'll do the changes soon and submit a PR

@Devamani11D done with the changes. Kindly merge it and assign me labels!

**Review by Devamani11D — APPROVED** [review]
@neeru24
It looks good.
Thank you for your contributions. :rocket:
Please feel free to contribute furthur.

**Pull request merged**
