### PR TITLE
Add code of conduct

### PR DESCRIPTION
**Pull request by shubhagarwal1**
Added code of conduct file to the project
Please approve my PR @ajaynegi45

### CODE REVIEW

**Review by ajaynegi45 — APPROVED** [review]
Hi @shubhagarwal1,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I'm pleased to inform you that I have merged your pull request. Your changes looks fantastic, and it aligns perfectly with the project's design and usability goals. Great job!

If you have any more contributions or if there's anything else you'd like to work on in the future, please don't hesitate to let us know. Your efforts are valuable to the project's success.

Once again, thank you for your contribution! ❤️

**Comment by ajaynegi45** [comment]
> Thank you kindly @ajaynegi45 i request yo to put labels, level label is very important for me

What is level label?

**Comment by shubhagarwal1** [comment]
> > Thank you kindly @ajaynegi45 i request yo to put labels, level label is very important for me
> 
Screenshot 2024-10-02 at 2 54 43 PM

> What is level label?

like this you can set level as you want but please assign a level label @ajaynegi45

**Comment by ajaynegi45** [comment]
> > > Thank you kindly @ajaynegi45 i request yo to put labels, level label is very important for me
> 
> Screenshot 2024-10-02 at 2 54 43 PM
> 
> > What is level label?
> 
> like this you can set level as you want but please assign a level label @ajaynegi45

what is purpose of it and why?

**Comment by shubhagarwal1** [comment]
> > > > > > Thank you kindly @ajaynegi45 i request yo to put labels, level label is very important for me
> > > > 
> > > > 
> > > > Screenshot 2024-10-02 at 2 54 43 PM
> > > > > What is level label?
> > > > 
> > > > 
> > > > like this you can set level as you want but please assign a level label @ajaynegi45
> > > 
> > > 
> > > what is purpose of it and why?
> > 
> > 
> > the main purpose of this tag is, getting poits level1 15 points level2 25 points level3 35 points
> > i am not sure about the scoring points exactly but it is how it works @ajaynegi45
> 
> I’ll mention that, but before I do, could you let me know where you got this information and who is responsible for assigning these points? Could you explain the details so I can implement it consistently across all my projects?

i got to know about this in gssoc discord channel @ajaynegi45

**Comment by shubhagarwal1** [comment]
hey please add level tag the level tag is assigned to the issue but not here please add it 
issue: #40

**Comment by ajaynegi45** [comment]
> hey please add level tag the level tag is assigned to the issue but not here please add it issue: #40

Already added

**Pull request merged**
