### PR TITLE
Update Book.java

### PR DESCRIPTION
**Pull request by Tanisha0708**
Added private String keyword; to hold the keyword information. Added getKeyword and setKeyword methods.
Fixed the toString method to properly display keyword. by using the keyword it will be easy to search book

### CODE REVIEW

**Comment by Tanisha0708** [comment]
@ajaynegi45 once go through this change

**Review by ajaynegi45 — APPROVED** [review]
Hi @Tanisha0708,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I'm pleased to inform you that I have merged your pull request. Your changes looks fantastic, and it aligns perfectly with the project's design and usability goals. Great job!

If you have any more contributions or if there's anything else you'd like to work on in the future, please don't hesitate to let us know. Your efforts are valuable to the project's success.

Once again, thank you for your contribution! ❤️

**Review by Devamani11D — APPROVED** [review]
Cool!!

**Comment by Devamani11D** [comment]
@ajaynegi45 Why there is no merge option here?

**Comment by Guhapriya01** [comment]
@Tanisha0708, great job adding the **keyword** attribute to the `Book` class! I wanted to point out that we’ll also need to update other classes (like `BookDto` and `BookService`) to accommodate this change.

**Comment by Guhapriya01** [comment]
@ajaynegi45, since you approved this PR, could you please take a look at it?

**Comment by ajaynegi45** [comment]
> @Tanisha0708, great job adding the **keyword** attribute to the `Book` class! I wanted to point out that we’ll also need to update other classes (like `BookDto` and `BookService`) to accommodate this change.

@Tanisha0708, accommodate this change in pr

**Comment by Tanisha0708** [comment]
@ajaynegi45 once go through the pull request . i did some changes in BookDto and BookService

**Pull request closed without merging**
