### PR TITLE
Implement GitHub PR Issue Checker Workflow

### PR DESCRIPTION
**Pull request by smog-root**
**Fixes** #76 

**Usage:**

1. When a pull request is created or edited, the workflow automatically triggers.

2. The workflow checks for:
- A non-empty PR description.
- A valid issue reference format (`Fixes #<issue-number>` or `Fixes #NEW`).
3. If either check fails, the PR will be marked as failing, and the author will receive clear error messages in the PR comments.
4. If all checks pass, a confirmation message will indicate that the PR is valid.

**_Note_**: Kindly add all the labels added to the issue, to this PR!

@ajaynegi45

### CODE REVIEW

**Review by MastanSayyad — COMMENTED** [review]
Hi @ajaynegi45 Program Manager this side

Workflows should be given level 1, therefore reduce this to level 1

image

**Comment by ajaynegi45** [comment]
> Hi @ajaynegi45 Program Manager this side
> 
> Workflows should be given level 1, therefore reduce this to level 1
> 
> image

Okay

**Comment by ajaynegi45** [comment]
> Hi @ajaynegi45 Program Manager this side
> 
> Workflows should be given level 1, therefore reduce this to level 1
> 
> image

I want to ask that where is my project mentor. All the assigned mentor are not interesting in working. They just join it for badge. Kindly take action on this matter also.

**Comment by MastanSayyad** [comment]
@ajaynegi45 sure

**Pull request merged**
