### PR TITLE
Done some enhancements and also added some new sections

### PR DESCRIPTION
**Pull request by milansamuel609**
I have done some enhancements and also added some new sections in the contributing.md file.

Done the following changes :-

1) Added code of conduct that you have provided in the readme also
2) Added need with the basic section
3) Enhanced the project structure
4) Added project structure section
5) Added additional method of contributing through GitHub desktop section
6) Added good coding practices section
7) Added the help and support section
8) Added the pull request section
9) Added issue report process section

fixes:[#77 ]
closes:[#77 ]

<br>

image

image

image

image

image

### CODE REVIEW

**Comment by milansamuel609** [comment]
@ajaynegi45 I have done the enhancements. Please kindly check it once if the changes are ok .

**Comment by milansamuel609** [comment]
If the changes done are fine please merge them.

**Review by ajaynegi45 — APPROVED** [review]
Hi @milansamuel609,

Thank you for your prompt work on this issue. I appreciate your dedication to the project.

I have reviewed your work, and I'm pleased to inform you that I have merged your pull request. Your changes looks fantastic, and it aligns perfectly with the project's design and usability goals. Great job!

If you have any more contributions or if there's anything else you'd like to work on in the future, please don't hesitate to let us know. Your efforts are valuable to the project's success.

Once again, thank you for your contribution! ❤️

**Comment by milansamuel609** [comment]
> Hi @milansamuel609,
> 
> Thank you for your prompt work on this issue. I appreciate your dedication to the project.
> 
> I have reviewed your work, and I'm pleased to inform you that I have merged your pull request. Your changes looks fantastic, and it aligns perfectly with the project's design and usability goals. Great job!
> 
> If you have any more contributions or if there's anything else you'd like to work on in the future, please don't hesitate to let us know. Your efforts are valuable to the project's success.
> 
> Once again, thank you for your contribution! ❤️

Thank you so much for this appreciation. Also for sure I will try to contribute in the future developments also 👍.

**Comment by milansamuel609** [comment]
This PR is not calculated as my contribution. Can you please assign this to me and add the label as gssoc extended.

**Comment by milansamuel609** [comment]
@ajaynegi45 Please kindly add the gssoc extend and level label in this PR.

**Pull request merged**
